Repository crate/cratedb-guide, pull requests merged in 2024-02, with the labels that each got.

#8 Adjust "machine data" mention
  docs/index.rst
Labels: documentation

#47 README: Use Markdown
  README.md
  README.rst
Labels: refactoring, guidance

#41 Performance: Reference articles about performance tricks for SQL SELECT queries
  docs/admin/performance/selects.rst
Labels: cross linking, new content

#43 Administration/Upgrading: Add index page for "Upgrading" section
  docs/admin/index.rst
  docs/admin/upgrade/full.rst
  docs/admin/upgrade/index.md
  docs/admin/upgrade/planning.rst
  docs/admin/upgrade/rolling.rst
Labels: sanding-1200, guidance

#45 Performance: Add links to downsampling tutorials
  docs/performance/selects.rst
Labels: cross linking, new content
