Repository crate/cratedb-guide, pull requests merged in 2024-11, with the labels that each got.

#132 ML/LlamaIndex: Add section about example program accompanying tutorial
  docs/domain/index.md
  docs/domain/ml/index.md
Labels: good first issue, cross linking, cla-signed

#134 Feature/Geo: Cleanups. Add "Plane Spotting with CrateDB" video.
  docs/feature/search/geo/index.md
Labels: sanding-1200, cross linking, cla-signed

#135 Feature/Connectivity: Rework page
  docs/feature/connectivity/index.md
Labels: sanding-180, refactoring, cross linking, guidance, cla-signed

#133 Domain/Time Series: Improve "Time Series Fundamentals with CrateDB" page
  docs/_include/card/timeseries-dask.md
  docs/_include/card/timeseries-intro.md
  docs/_include/links.md
  docs/domain/timeseries/fundamentals.md
  docs/domain/timeseries/index.md
  docs/domain/timeseries/learn/query.md
Labels: sanding-500, cross linking, cla-signed

#131 Home: Add card with reference to "All Features" page
  docs/home/index.md
Labels: good first issue, cross linking, guidance, cla-signed

#140 Home: Fix syntax on landing page update
  docs/home/index.md
Labels: cla-signed

#139 Home: Update the landing page to align with the marketing messaging
  docs/home/index.md
Labels: cla-signed

#144 Feature/Search/Vector: Educate about `VECTOR_SIMILARITY` function
  docs/feature/search/vector/index.md
Labels: cla-signed

#143 Home: Break down wall of text in "CrateDB Cloud" card
  docs/home/index.md
Labels: cla-signed
